name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for commit linting and semantic-release
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node_version }}"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install canvas tools to build from source # TODO: remove this once canvas releases a prebuild
        if: ${{ matrix.node_version == '18' }}
        run: |
          sudo apt update
          sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev      
            
      - name: Install dependencies
        run: npm ci

      - name: Bootstrap
        run: npx lerna bootstrap --hoist

      - name: Build
        run: npx lerna run build

      - name: Test
        run: npx lerna run test

